export const mockJobs = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    company: "TechNova Inc.",
    logo: "TN",
    logoColor: "bg-blue-100 text-blue-700",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Engineering",
    salary: "$120k – $160k",
    experience: "5+ years",
    posted: "2 days ago",
    description: "We are looking for a Senior Frontend Developer to join our growing team. You'll work on building scalable web applications using React, TypeScript, and modern tooling.",
    requirements: ["React", "TypeScript", "GraphQL", "CSS/Tailwind", "5+ years exp"],
    featured: true,
    remote: true,
  },
  {
    id: 2,
    title: "Product Designer",
    company: "DesignHub",
    logo: "DH",
    logoColor: "bg-purple-100 text-purple-700",
    location: "New York, NY",
    type: "Full-time",
    category: "Design",
    salary: "$90k – $120k",
    experience: "3+ years",
    posted: "1 day ago",
    description: "DesignHub is seeking a talented Product Designer to shape the future of our product. You'll collaborate with engineers and product managers.",
    requirements: ["Figma", "User Research", "Prototyping", "Design Systems", "3+ years exp"],
    featured: true,
    remote: false,
  },
  {
    id: 3,
    title: "Backend Engineer",
    company: "CloudStack",
    logo: "CS",
    logoColor: "bg-green-100 text-green-700",
    location: "Austin, TX",
    type: "Full-time",
    category: "Engineering",
    salary: "$110k – $145k",
    experience: "4+ years",
    posted: "3 days ago",
    description: "Join CloudStack as a Backend Engineer and help us scale our infrastructure to millions of users.",
    requirements: ["Node.js", "PostgreSQL", "AWS", "Redis", "Docker"],
    featured: false,
    remote: true,
  },
  {
    id: 4,
    title: "Data Scientist",
    company: "DataMinds",
    logo: "DM",
    logoColor: "bg-yellow-100 text-yellow-700",
    location: "Seattle, WA",
    type: "Full-time",
    category: "Data Science",
    salary: "$130k – $170k",
    experience: "3+ years",
    posted: "5 days ago",
    description: "DataMinds is looking for a Data Scientist to help us derive insights from large datasets and build predictive models.",
    requirements: ["Python", "TensorFlow", "SQL", "Statistics", "ML"],
    featured: false,
    remote: true,
  },
  {
    id: 5,
    title: "Marketing Manager",
    company: "GrowthLabs",
    logo: "GL",
    logoColor: "bg-red-100 text-red-700",
    location: "Chicago, IL",
    type: "Full-time",
    category: "Marketing",
    salary: "$80k – $110k",
    experience: "4+ years",
    posted: "1 week ago",
    description: "GrowthLabs needs a Marketing Manager to lead our campaigns and drive customer acquisition.",
    requirements: ["SEO/SEM", "Content Strategy", "Analytics", "Team Leadership"],
    featured: false,
    remote: false,
  },
  {
    id: 6,
    title: "DevOps Engineer",
    company: "InfraCore",
    logo: "IC",
    logoColor: "bg-indigo-100 text-indigo-700",
    location: "Remote",
    type: "Contract",
    category: "Engineering",
    salary: "$100k – $130k",
    experience: "3+ years",
    posted: "4 days ago",
    description: "InfraCore is looking for a DevOps Engineer to manage CI/CD pipelines and cloud infrastructure.",
    requirements: ["Kubernetes", "Terraform", "CI/CD", "AWS/GCP", "Linux"],
    featured: false,
    remote: true,
  },
];

export const categories = [
  { name: "Engineering", icon: "💻", count: 1240 },
  { name: "Design", icon: "🎨", count: 380 },
  { name: "Marketing", icon: "📊", count: 520 },
  { name: "Data Science", icon: "📈", count: 290 },
  { name: "Finance", icon: "💰", count: 410 },
  { name: "Healthcare", icon: "🏥", count: 670 },
  { name: "Sales", icon: "🤝", count: 330 },
  { name: "Education", icon: "📚", count: 200 },
];

export const testimonials = [
  {
    name: "Sarah Chen",
    role: "Frontend Developer at Google",
    avatar: "SC",
    text: "JobConnect helped me land my dream job at Google. The platform is intuitive and the job matching is spot on.",
  },
  {
    name: "Marcus Williams",
    role: "Product Manager at Airbnb",
    avatar: "MW",
    text: "I found my role within 3 weeks of signing up. The resume builder and direct apply features are game changers.",
  },
  {
    name: "Priya Nair",
    role: "Data Scientist at Meta",
    avatar: "PN",
    text: "The job alerts kept me informed about relevant openings. Highly recommend for anyone in tech.",
  },
];
